#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "🚀 Initiating code checks..."

FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

# Check ESLint standards on staged files
echo "$FILES" | xargs ./node_modules/.bin/eslint --format=pretty --quiet '*' ||
(
	echo "🚨 Whoops! Code style violation detected 🤖. Fix it with 'npm run format', add changes, and try again."
	false;
)

# If everything passes... Now we can commit
echo "✅ Code checks successful! 🤖 Initiating commit sequence..."
